# "project_id": "591191"
project_id: '592283'
# "api_token": "56b15b639de15b35cfc4e6d6ee85b9a7bb141675fba1ab0e787f4b0d69b2a6ffae8eb0e19dc0706f"
api_token: 56b15b639de15b35cfc4e6d6ee85b9a7bb141675fba1ab0e787f4b0d69b2a6ffae8eb0e19dc0706f
# "preserve_hierarchy": true
preserve_hierarchy: true
# "base_url": "https://api.crowdin.com"         # https://{organization-name}.crowdin.com for Crowdin Enterprise

files: 
  # - source: /docs/DeepLearning/cs231n/**/*                                   #source files filter
  #   translation: /i18n/%osx_locale%/docusaurus-plugin-content-docs/current/%original_path%/%original_file_name%       #where translations are stored
  #   # translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # - source: /i18n/en/**/*
  #   translation: /i18n/%two_letters_code%/%original_path%/%original_file_name%
    # - source: /i18n/en/**/*
      # translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
    - source: /docs/en/**/*
      translation: /docs/%locale%/**/%original_file_name%
  # {
  #   "source": "/i18n/en/**/*",
  #   "translation": "/i18n/zh/docusaurus-plugin-content-docs/current/**/%original_file_name%"
  # }

# "files": [
#   {
#     "source": "/docs/深度学习/cs231n/**/*",                                       #source files filter
#     "translation": "/i18n/%osx_locale%/docusaurus-plugin-content-docs/current/DeepLearning/cs231n/**/%original_file_name%"       #where translations are stored
#   },
#   # {
#   #   "source": "/i18n/en/**/*",
#   #   "translation": "/i18n/zh/docusaurus-plugin-content-docs/current/**/%original_file_name%"
#   # }
# ]

# api_token: 56b15b639de15b35cfc4e6d6ee85b9a7bb141675fba1ab0e787f4b0d69b2a6ffae8eb0e19dc0706f
# project_id: '591191'
# api_token_env: CROWDIN_PERSONAL_TOKEN
# preserve_hierarchy: true
# files:
#   # JSON 翻译文件
#   - source: /i18n/en/**/*
#     translation: /i18n/zh/**/%original_file_name%
#   # Markdown 文档文件 
#   - source: /i18n/en/**/*
#     translation: /i18n/zh/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Markdown 博客文件
  # - source: /blog/**/*
  #   translation: /i18n/zh/docusaurus-plugin-content-blog/**/%original_file_name%