site_name: CS231n
site_url: https://eanyang7.github.io/cs231n
site_description: "CS231n: Deep Learning for Computer Vision"
repo_url: https://github.com/EanYang7/cs231n
repo_name: EanYang7/cs231n

theme:
  language: zh 
  name: material
  custom_dir: overrides
  logo: logo.jpg
  favicon: logo.jpg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换为暗黑模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式
  # 设置右上角图标
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  - toc:
      permalink: ⚓︎
  
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - git-revision-date-localized:
    enable_creation_date: true
 - search:
    separator: '[\s\u200b\-]'
  


edit_uri: "edit/dev/docs/"

nav:
  - 首页: 
    - 'index.md'

  - 课程: 
    - 准备工作:
      - 软件设置: './courses/preparation/setup.md'
      - Python/Numpy教程: './courses/preparation/python-numpy-tutorial.md'
    - 神经网络:  
        - 图像分类: './courses/neural_network/classification.md'
        - 线性分类: './courses/neural_network/linear-classify.md'
        - 优化：随机梯度下降 : './courses/neural_network/optimization-1.md'
        - 反向传播: './courses/neural_network/optimization-2.md'
        - 神经网络: 
          - 创建结构: './courses/neural_network/neural-networks-1.md'
          - 创建数据和损失: './courses/neural_network/neural-networks-2.md'
          - 学习和评估: './courses/neural_network/neural-networks-3.md'
        - 最小神经网络案例研究: './courses/neural_network/neural-networks-case-study.md'
    - 卷积神经网络: 
        - 结构、卷积/池化层: './courses/CNN/convolutional-networks.md'
        - 理解与可视化: './courses/CNN/understanding-cnn.md'
        - 迁移学习与微调: './courses/CNN/transfer-learning.md'
  - 任务: 
    - 任务1: './assignments/2023/assignment1.md'
    - 任务2: './assignments/2023/assignment2.md'
    - 任务2: './assignments/2023/assignment3.md'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EanYang7/cs231n
  alternate:
    - name: 中文
      link: /cs231n/
      lang: zh
    - name: English(源网站)
      link: https://cs231n.github.io/
      lang: en
  # generator: false  
  analytics:
    provider: google
    property: G-5F8XNH7BCX
    feedback:
      title: 对当前页面有任何疑问吗？
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            感谢您的反馈！请点击这里<a href="https://github.com/EanYang7/cs231n/issues" target="_blank" rel="noopener">这里</a>提供问题反馈.
   