site_name: CS231n
site_url: https://eanyang7.github.io/cs231n
site_description: "CS231n: Deep Learning for Computer Vision"
repo_url: https://github.com/EanYang7/cs231n
repo_name: EanYang7/cs231n

theme:
  language: zh 
  name: material
  logo: logo.jpg
  favicon: logo.jpg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.action.edit
    - content.action.view

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换为暗黑模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式
  # 设置右上角图标
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  - toc:
      permalink: ⚓︎
  
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - git-revision-date-localized:
    enable_creation_date: true
 - search


edit_uri: "edit/dev/docs/"

nav:
  - 首页: 
    - '/cs231n/index.md'

  - 课程: 
    - 准备工作:
      - 软件设置: 'setup.md'
      - Python Numpy教程: 'python-numpy-tutorial.md'
    - 神经网络:  
        - 图像分类: 'classification.md'
        - 线性分类: 'linear-classify.md'
        - 优化 : 
          - 'optimization-1.md'
          - 'optimization-2.md'
        - 神经网络: 
          - 'neural-networks-1.md'
          - 'neural-networks-2.md'
          - 'neural-networks-3.md'
        - neural-networks-case-study: 'neural-networks-case-study.md'
    - 卷积神经网络: 
        - 'convolutional-networks.md'
        - 'understanding-cnn.md'
        - 'transfer-learning.md'
  - 作业: 
    - 作业1: './assignments/2023/assignment1.md'
    - 作业2: './assignments/2023/assignment2.md'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EanYang7/cs231n
  generator: false  
  alternate:
    - name: 中文
      link: /cs231n/zh-CN/ 
      lang: zh
    - name: English
      link: /cs231n/en/
      lang: en
   